### ISSUE TITLE
add Index data as well?

### ISSUE THREAD

**Issue by srbharadwaj** [NayakwadiS/mftool#4]
URL: https://www1.nseindia.com/products/dynaContent/equities/indices/total_returnindices.jsp?indexType={0}&fromDate={1}&toDate={2}
{0} -> NIFTY 100, NIFTY 50 etc..
{1} -> from date
{2} -> to date
https://www1.nseindia.com/products/dynaContent/equities/indices/total_returnindices.jsp?indexType=NIFTY%2050&fromDate=21-04-2014&toDate=16-04-2015

Just one API - getHistoricNiftyData(index)

**Comment by NayakwadiS** [comment]
Is it correct way to add Nifty/Stock API in **Mutual fund** library ?

**Comment by srbharadwaj** [comment]
Yes i feel index is required if we want to compare mf with so an option is a good idea

**Comment by NayakwadiS** [comment]
OK we will add Nifty API, but site https://www1.nseindia.com will not available after Aug'20.
Do we have any other way to get this data.

**Comment by srbharadwaj** [comment]
need to check let me know if the above link stops working

**Comment by tarakbluru** [comment]
Thanks @NayakwadiS  for developing this and making it open source.

https://www.youtube.com/watch?v=vQRLBGpCg9I
has solution for getting nse data .

Only indices (sectoral and few broad based) would be a good idea.

If possible, it would be great to convert the NAV prices into OHLC format (daily NAV prices converted to weekly/monthly ohlc).

Screen shot from define edge attached.

![define_ege](https://user-images.githubusercontent.com/1935750/92204434-20767180-eea1-11ea-8150-2f609c9266d6.png)

I understand mftools today is giving out basic quote (on the lines of nsetools).  To get the best out of mftools, ohlc data would be highly useful.  This is because there are no intraday players or swing (few days) players here. It is mostly weekly and monthly and for them this would help a lot.

**Comment by tarakbluru** [comment]
For scheme codes,  link on the amfi would be a great idea. link [here](https://www.amfiindia.com/spages/NAVOpen.txt)

**Comment by tarakbluru** [comment]
> 
> 
> Thanks @NayakwadiS for developing this and making it open source.
> 
> https://youtu.be/vQRLBGpCg9I might be helpful here.
> 
> I think eod data will definitely be available on NSE server. Only indices (sectoral and few broad based) would be good enough.
> 
> If possible, it would be great to convert the NAV prices into OHLC format (daily NAV prices converted to weekly/monthly ohlc).
> 
> Screen shot from define edge attached.
> 
> ![define_ege](https://user-images.githubusercontent.com/1935750/92204434-20767180-eea1-11ea-8150-2f609c9266d6.png)
> 
> I understand mftools today is giving out basic quote (on the lines of nsetools). To get the best out of mftools, ohlc data would be highly useful. This is because there are no intraday players or swing (few days) players here. It is mostly weekly and monthly and for them ohlc would help a lot. That data can be taken either to Amibroker (etc..) or even processed using python finance tools.
> 
> Best regards,

Along with the MF data, it would be helpful to have NIFTY P/E data (https://www1.nseindia.com/products/content/equities/indices/historical_pepb.htm).

**Comment by NayakwadiS** [comment]
Guys,

1. To get Index data in very precise format there are other python packages available.
2. Using scripts to get info or data from New NSE website is not permitted. [here](https://archives.nseindia.com/content/circulars/WEB45032.pdf)
3.  mftool is mean to get NAV's only. Data Analysis and Visualization are the part of personal projects.

Thanks

**Comment by NayakwadiS** [comment]
conversion of NAV to OHLC is somehow difficult but if would like you can check [this](https://github.com/NayakwadiS/Forecasting_Mutual_Funds)
